# Generated by Django 3.0.7 on 2020-09-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_master',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='raw_master',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='squ_master',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vendor_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=30)),
                ('vaddress', models.TextField()),
                ('vphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='raw_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('payment', models.CharField(max_length=10)),
                ('rmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.raw_master')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.squ_master')),
                ('vmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.vendor_master')),
            ],
        ),
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('raw_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.raw_master')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.squ_master')),
            ],
        ),
    ]
