# Generated by Django 3.0.7 on 2020-09-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_data',
            name='payment',
            field=models.CharField(choices=[('paid', 'Paid'), ('credit', 'Credit')], default='credit', max_length=6),
        ),
    ]
