# Generated by Django 3.0.7 on 2020-09-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200907_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('caddress', models.TextField()),
                ('cphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('payment', models.CharField(choices=[('paid', 'Paid'), ('credit', 'Credit')], default='credit', max_length=6)),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.customer_master')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.product_master')),
            ],
        ),
    ]
